import React, { useState } from 'react';
import {
    Box,
    TextField,
    Button,
    IconButton,
    useMediaQuery
} from "@mui/material";
import { Formik } from "formik";
import TimesheetWrapper from "components/TimesheetWrapper";
import './Timesheet.css'

//gotta make it more efficient somehow cause it laggs when typing 
const Days = (props) => {
    const { handleTimesheet, initialValuesTimesheet, timesheetSchema, isNonMobileScreens, palette } = props

    return (
        <Formik
            onSubmit={handleTimesheet}
            initialValues={initialValuesTimesheet}
            validationSchema={timesheetSchema}
        >
            {({
                values,
                errors,
                touched,
                handleBlur,
                handleChange,
                handleSubmit,
                setFieldValue,
                resetForm
            }) => (
                <form onSubmit={handleSubmit}>
                    <Box
                        display="grid"
                        sx={{
                            "& > div": {gridColumn: isNonMobileScreens ? undefined : "span 4"}
                        }}
                        id="timesheet"
                    >
                        <TimesheetWrapper >
                            <TextField 
                                label="First Name"
                                onBlur={handleBlur}
                                onChange={handleChange}
                                value={values.firstName}
                                name="firstName"
                                error={Boolean(touched.firstName) && Boolean(errors.firstName)}
                                helperText={touched.firstName && errors.firstName}
                            />
                            <TextField 
                                label="Last Name"
                                onBlur={handleBlur}
                                onChange={handleChange}
                                value={values.lastName}
                                name="lastName"
                                error={Boolean(touched.lastName) && Boolean(errors.lastName)}
                                helperText={touched.lastName && errors.lastName}
                            />   
                            <TextField 
                                label="Employee Number"
                                onBlur={handleBlur}
                                onChange={handleChange}
                                value={values.employeeNumber}
                                name="employeeNumber"
                                error={Boolean(touched.employeeNumber) && Boolean(errors.employeeNumber)}
                                helperText={touched.employeeNumber && errors.employeeNumber}
                            /> 
                            <TextField 
                                label="Period Starting"
                                onBlur={handleBlur}
                                onChange={handleChange}
                                value={values.periodStarting}
                                name="periodStarting"
                                error={Boolean(touched.periodStarting) && Boolean(errors.periodStarting)}
                                helperText={touched.periodStarting && errors.periodStarting}
                            />   
                            <TextField 
                                label="Period Ending"
                                onBlur={handleBlur}
                                onChange={handleChange}
                                value={values.periodEnding}
                                name="periodEnding"
                                error={Boolean(touched.periodEnding) && Boolean(errors.periodEnding)}
                                helperText={touched.periodEnding && errors.periodEnding}
                            />  
                            <table>
                                <tbody>
                                    <tr>
                                        <th></th>
                                        <th>Fri</th>
                                        <th>Sat</th>
                                        <th>Sun</th>
                                        <th>Mon</th>
                                        <th>Tue</th>
                                        <th>Wed</th>
                                        <th>Thu</th>
                                        <th>Fri</th>
                                        <th>Sat</th>
                                        <th>Sun</th>
                                        <th>Mon</th>
                                        <th>Tue</th>
                                        <th>Wed</th>
                                        <th>Thu</th>
                                    </tr>
                                    {/* <tr>
                                        <th></th>
                                        <th>4/10</th>
                                        <th>4/11</th>
                                        <th>4/12</th>
                                        <th>4/13</th>
                                        <th>4/14</th>
                                        <th>4/15</th>
                                        <th>4/16</th>
                                        <th>4/17</th>
                                        <th>4/18</th>
                                        <th>4/19</th>
                                        <th>4/20</th>
                                        <th>4/21</th>
                                        <th>4/22</th>
                                        <th>4/23</th>
                                    </tr> */}
                                    <tr>
                                        <th>In</th>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday1.clockIn1}
                                                name="friday1.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday1.clockIn1}
                                                name="saturday1.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday1.clockIn1}
                                                name="sunday1.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday1.clockIn1}
                                                name="monday1.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday1.clockIn1}
                                                name="tuesday1.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday1.clockIn1}
                                                name="wednesday1.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday1.clockIn1}
                                                name="thursday1.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday2.clockIn1}
                                                name="friday2.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday2.clockIn1}
                                                name="saturday2.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday2.clockIn1}
                                                name="sunday2.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday2.clockIn1}
                                                name="monday2.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday2.clockIn1}
                                                name="tuesday2.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday2.clockIn1}
                                                name="wednesday2.clockIn1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday2.clockIn1}
                                                name="thursday2.clockIn1"
                                            /></td>
                                    </tr>
                                    <tr>
                                        <th>Out</th>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday1.clockOut1}
                                                name="friday1.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday1.clockOut1}
                                                name="saturday1.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday1.clockOut1}
                                                name="sunday1.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday1.clockOut1}
                                                name="monday1.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday1.clockOut1}
                                                name="tuesday1.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday1.clockOut1}
                                                name="wednesday1.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday1.clockOut1}
                                                name="thursday1.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday2.clockOut1}
                                                name="friday2.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday2.clockOut1}
                                                name="saturday2.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday2.clockOut1}
                                                name="sunday2.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday2.clockOut1}
                                                name="monday2.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday2.clockOut1}
                                                name="tuesday2.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday2.clockOut1}
                                                name="wednesday2.clockOut1"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday2.clockOut1}
                                                name="thursday2.clockOut1"
                                            /></td>
                                    </tr>
                                    <tr>
                                        <th>In</th>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday1.clockIn2}
                                                name="friday1.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday1.clockIn2}
                                                name="saturday1.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday1.clockIn2}
                                                name="sunday1.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday1.clockIn2}
                                                name="monday1.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday1.clockIn2}
                                                name="tuesday1.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday1.clockIn2}
                                                name="wednesday1.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday1.clockIn2}
                                                name="thursday1.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday2.clockIn2}
                                                name="friday2.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday2.clockIn2}
                                                name="saturday2.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday2.clockIn2}
                                                name="sunday2.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday2.clockIn2}
                                                name="monday2.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday2.clockIn2}
                                                name="tuesday2.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday2.clockIn2}
                                                name="wednesday2.clockIn2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday2.clockIn2}
                                                name="thursday2.clockIn2"
                                            /></td>
                                    </tr>
                                    <tr>
                                        <th>Out</th>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday1.clockOut2}
                                                name="friday1.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday1.clockOut2}
                                                name="saturday1.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday1.clockOut2}
                                                name="sunday1.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday1.clockOut2}
                                                name="monday1.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday1.clockOut2}
                                                name="tuesday1.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday1.clockOut2}
                                                name="wednesday1.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday1.clockOut2}
                                                name="thursday1.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday2.clockOut2}
                                                name="friday2.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday2.clockOut2}
                                                name="saturday2.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday2.clockOut2}
                                                name="sunday2.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday2.clockOut2}
                                                name="monday2.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday2.clockOut2}
                                                name="tuesday2.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday2.clockOut2}
                                                name="wednesday2.clockOut2"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday2.clockOut2}
                                                name="thursday2.clockOut2"
                                            /></td>
                                    </tr>
                                    <tr>
                                        <th>Total</th>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday1.total}
                                                name="friday1.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday1.total}
                                                name="saturday1.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday1.total}
                                                name="sunday1.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday1.total}
                                                name="monday1.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday1.total}
                                                name="tuesday1.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday1.total}
                                                name="wednesday1.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday1.total}
                                                name="thursday1.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday2.total}
                                                name="friday2.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday2.total}
                                                name="saturday2.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday2.total}
                                                name="sunday2.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday2.total}
                                                name="monday2.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday2.total}
                                                name="tuesday2.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday2.total}
                                                name="wednesday2.total"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday2.total}
                                                name="thursday2.total"
                                            /></td>
                                    </tr>
                                    <tr>
                                        <th>Leave</th>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday1.leave}
                                                name="friday1.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday1.leave}
                                                name="saturday1.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday1.leave}
                                                name="sunday1.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday1.leave}
                                                name="monday1.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday1.leave}
                                                name="tuesday1.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday1.leave}
                                                name="wednesday1.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday1.leave}
                                                name="thursday1.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.friday2.leave}
                                                name="friday2.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.saturday2.leave}
                                                name="saturday2.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.sunday2.leave}
                                                name="sunday2.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.monday2.leave}
                                                name="monday2.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.tuesday2.leave}
                                                name="tuesday2.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.wednesday2.leave}
                                                name="wednesday2.leave"
                                            /></td>
                                        <td><TextField 
                                                onBlur={handleBlur}
                                                onChange={handleChange}
                                                value={values.thursday2.leave}
                                                name="thursday2.leave"
                                            /></td>
                                    </tr>
                                </tbody>
                            </table>  
                            <Button
                                type="submit"
                                sx={{
                                    color: palette.background.alt,
                                    backgroundColor: palette.primary.main,
                                    borderRadius: "3rem"
                                }}
                            >
                                Submit
                            </Button>
                        </TimesheetWrapper>
                    </Box>
                </form>
            )}
            
        </Formik>
  );
}

export default Days;